# frozen_string_literal: true
# Seeds for a PerformerRole model in a standard Relational Database
# Schema is:
# PerformerRole { description: 'String', ppl_code: 'String', active: 'Boolean' }
#
[
  {description: "Anatara", ppl_code: "AAA", active: true},
  {description: "Acoustic Bass Guitar", ppl_code: "ABG", active: true},
  {description: "Accordion", ppl_code: "ACC", active: true},
  {description: "Atchere", ppl_code: "ACH", active: true},
  {description: "Accompanist", ppl_code: "ACM", active: true},
  {description: "Alto Crumhorn", ppl_code: "ACR", active: true},
  {description: "Actor", ppl_code: "ACT", active: true},
  {description: "Adufe", ppl_code: "ADF", active: true},
  {description: "Aeolian Harp", ppl_code: "AEO", active: true},
  {description: "Andean Flute", ppl_code: "AFL", active: true},
  {description: "Afuche", ppl_code: "AFU", active: true},
  {description: "Algaita", ppl_code: "AGA", active: true},
  {description: "Agogo", ppl_code: "AGG", active: true},
  {description: "Apongalahy", ppl_code: "AGH", active: true},
  {description: "Acoustic Guitar", ppl_code: "AGT", active: true},
  {description: "Andean Harp", ppl_code: "AHA", active: true},
  {description: "African Congo Drums", ppl_code: "AKD", active: true},
  {description: "Aketse", ppl_code: "AKE", active: true},
  {description: "Angklung", ppl_code: "AKL", active: true},
  {description: "Alto Clarinet", ppl_code: "ALC", active: true},
  {description: "Alto Flute", ppl_code: "ALF", active: true},
  {description: "Algoja", ppl_code: "ALG", active: true},
  {description: "Alto Horn", ppl_code: "ALH", active: true},
  {description: "Alphorn", ppl_code: "ALP", active: true},
  {description: "Alto (voice)", ppl_code: "ALT", active: true},
  {description: "Archlute", ppl_code: "ALU", active: true},
  {description: "Animal Sounds", ppl_code: "AMN", active: true},
  {description: "Ambtara", ppl_code: "AMO", active: true},
  {description: "Anglo-Concertina", ppl_code: "ANG", active: true},
  {description: "Anandalahari", ppl_code: "ANH", active: true},
  {description: "Animal Sounds Impersonator", ppl_code: "ANI", active: true},
  {description: "Announcer", ppl_code: "ANN", active: true},
  {description: "Appalachian Dulcimer", ppl_code: "APD", active: true},
  {description: "Arpeggione", ppl_code: "APE", active: true},
  {description: "Apentemma", ppl_code: "APT", active: true},
  {description: "Alto Recorder", ppl_code: "ARE", active: true},
  {description: "Arghul", ppl_code: "ARG", active: true},
  {description: "Asiko", ppl_code: "ASK", active: true},
  {description: "Alto Saxophone", ppl_code: "ASX", active: true},
  {description: "Alto Trombone", ppl_code: "ATR", active: true},
  {description: "Autoharp", ppl_code: "AUH", active: true},
  {description: "Alto Valve Trombone", ppl_code: "AVT", active: true},
  {description: "Babasa", ppl_code: "BAB", active: true},
  {description: "Bass Accordion", ppl_code: "BAC", active: true},
  {description: "Bagpipes", ppl_code: "BAG", active: true},
  {description: "Bajo", ppl_code: "BAJ", active: true},
  {description: "Banjo-Mandolin", ppl_code: "BAM", active: true},
  {description: "BARA", ppl_code: "BAR", active: true},
  {description: "Bass", ppl_code: "BAS", active: true},
  {description: "Bata", ppl_code: "BAT", active: true},
  {description: "Bombo (Mouth Bom)", ppl_code: "BBB", active: true},
  {description: "Bombo (Bass Drum)", ppl_code: "BBD", active: true},
  {description: "Bombo (Frame Drum)", ppl_code: "BBF", active: true},
  {description: "Boobams", ppl_code: "BBM", active: true},
  {description: "Bombo?", ppl_code: "BBO", active: true},
  {description: "Bambaro", ppl_code: "BBR", active: true},
  {description: "Brass", ppl_code: "BBS", active: true},
  {description: "Bass-Baritone (voice)", ppl_code: "BBT", active: true},
  {description: "Beat Box", ppl_code: "BBX", active: true},
  {description: "Boys' Choir Director", ppl_code: "BCD", active: true},
  {description: "Bass Crumhorn", ppl_code: "BCR", active: true},
  {description: "Bass Concertina", ppl_code: "BCT", active: true},
  {description: "Bandola", ppl_code: "BDA", active: true},
  {description: "Bass Dulcian", ppl_code: "BDC", active: true},
  {description: "Bodhr n", ppl_code: "BDH", active: true},
  {description: "Bandol-n", ppl_code: "BDN", active: true},
  {description: "Bandonen", ppl_code: "BDO", active: true},
  {description: "Bandora", ppl_code: "BDR", active: true},
  {description: "Banjo-Dulcimer", ppl_code: "BDU", active: true},
  {description: "Bells", ppl_code: "BEL", active: true},
  {description: "Bendir", ppl_code: "BEN", active: true},
  {description: "Berimbau", ppl_code: "BER", active: true},
  {description: "Bull Fiddle", ppl_code: "BFD", active: true},
  {description: "Bass Guitar", ppl_code: "BGT", active: true},
  {description: "Biniou", ppl_code: "BIU", active: true},
  {description: "Banjulele", ppl_code: "BJL", active: true},
  {description: "Bajo Sexto", ppl_code: "BJS", active: true},
  {description: "Bankia", ppl_code: "BKA", active: true},
  {description: "Bandleader", ppl_code: "BLD", active: true},
  {description: "Bass Lute", ppl_code: "BLE", active: true},
  {description: "Balafon", ppl_code: "BLF", active: true},
  {description: "Balalaika", ppl_code: "BLK", active: true},
  {description: "Baglama", ppl_code: "BLM", active: true},
  {description: "Bolon", ppl_code: "BLO", active: true},
  {description: "Bullroarer", ppl_code: "BLR", active: true},
  {description: "Bell Tree", ppl_code: "BLT", active: true},
  {description: "Bass Marimba", ppl_code: "BMA", active: true},
  {description: "Bembe", ppl_code: "BMB", active: true},
  {description: "Bongos", ppl_code: "BNG", active: true},
  {description: "Banjo", ppl_code: "BNJ", active: true},
  {description: "Bones", ppl_code: "BNS", active: true},
  {description: "Bo?", ppl_code: "BO_", active: true},
  {description: "Bo (Bell)", ppl_code: "BOB", active: true},
  {description: "Bo (Cymbals)", ppl_code: "BOC", active: true},
  {description: "Bo (Flute)", ppl_code: "BOF", active: true},
  {description: "Bombarde", ppl_code: "BOM", active: true},
  {description: "Bordonua", ppl_code: "BOR", active: true},
  {description: "Bouzouki", ppl_code: "BOU", active: true},
  {description: "Musical Box", ppl_code: "BOX", active: true},
  {description: "Body Percussion", ppl_code: "BPE", active: true},
  {description: "Barrel Piano", ppl_code: "BPN", active: true},
  {description: "Bandura", ppl_code: "BRA", active: true},
  {description: "Brass Bass", ppl_code: "BRB", active: true},
  {description: "Bass Recorder", ppl_code: "BRC", active: true},
  {description: "Bass Racket", ppl_code: "BRK", active: true},
  {description: "Broom", ppl_code: "BRM", active: true},
  {description: "Barrel Organ", ppl_code: "BRO", active: true},
  {description: "Border Pipes", ppl_code: "BRP", active: true},
  {description: "Bandurria", ppl_code: "BRR", active: true},
  {description: "Baritone Saxophone", ppl_code: "BRS", active: true},
  {description: "Baritone (voice)", ppl_code: "BRT", active: true},
  {description: "Baryton", ppl_code: "BRY", active: true},
  {description: "Bass Clarinet", ppl_code: "BSC", active: true},
  {description: "Bass Drum", ppl_code: "BSD", active: true},
  {description: "Bass Flute", ppl_code: "BSF", active: true},
  {description: "Basset Horn", ppl_code: "BSH", active: true},
  {description: "Bansuri Flute", ppl_code: "BSR", active: true},
  {description: "Bassoon", ppl_code: "BSS", active: true},
  {description: "Bass Saxophone", ppl_code: "BSX", active: true},
  {description: "Basy", ppl_code: "BSY", active: true},
  {description: "Button Accordion", ppl_code: "BTA", active: true},
  {description: "Bass Tuba", ppl_code: "BTB", active: true},
  {description: "Basset Clarinet", ppl_code: "BTC", active: true},
  {description: "Bass Tambura", ppl_code: "BTM", active: true},
  {description: "Baritone (Saxhorn)", ppl_code: "BTN", active: true},
  {description: "Bass Trumpet", ppl_code: "BTP", active: true},
  {description: "Bass Trombone", ppl_code: "BTR", active: true},
  {description: "Bottle", ppl_code: "BTT", active: true},
  {description: "Beat Box (Vocal)", ppl_code: "BTX", active: true},
  {description: "Bugle", ppl_code: "BUE", active: true},
  {description: "Backing Vocals", ppl_code: "BVC", active: true},
  {description: "Bass Viol", ppl_code: "BVL", active: true},
  {description: "Bass (voice)", ppl_code: "BVO", active: true},
  {description: "Biwa", ppl_code: "BWA", active: true},
  {description: "Bayan", ppl_code: "BYA", active: true},
  {description: "Bouz_r", ppl_code: "BZR", active: true},
  {description: "Caller", ppl_code: "CAL", active: true},
  {description: "Campana", ppl_code: "CAM", active: true},
  {description: "Cor Anglais", ppl_code: "CAN", active: true},
  {description: "Castanets", ppl_code: "CAS", active: true},
  {description: "Castrato (voice)", ppl_code: "CAT", active: true},
  {description: "Cavaquinho", ppl_code: "CAV", active: true},
  {description: "Contrabass Flute", ppl_code: "CBF", active: true},
  {description: "Calabash", ppl_code: "CBH", active: true},
  {description: "Cimbalom", ppl_code: "CBM", active: true},
  {description: "Chamber Organ", ppl_code: "CBO", active: true},
  {description: "Chamber Pipes", ppl_code: "CBP", active: true},
  {description: "Cabasa", ppl_code: "CBS", active: true},
  {description: "Cumbus", ppl_code: "CBU", active: true},
  {description: "Children's Choir Director", ppl_code: "CCD", active: true},
  {description: "Ceng Ceng", ppl_code: "CCE", active: true},
  {description: "Corno Da Caccia", ppl_code: "CDC", active: true},
  {description: "Choir Director", ppl_code: "CDI", active: true},
  {description: "Cyla-Diare", ppl_code: "CDR", active: true},
  {description: "Cello", ppl_code: "CEL", active: true},
  {description: "Cifteli", ppl_code: "CFT", active: true},
  {description: "Clog Dancer", ppl_code: "CGD", active: true},
  {description: "Changgo", ppl_code: "CGG", active: true},
  {description: "Charango", ppl_code: "CHA", active: true},
  {description: "Chamberlin", ppl_code: "CHB", active: true},
  {description: "Choral Conductor", ppl_code: "CHC", active: true},
  {description: "Chinese Drum", ppl_code: "CHD", active: true},
  {description: "Cheng", ppl_code: "CHG", active: true},
  {description: "Chinese Harp", ppl_code: "CHH", active: true},
  {description: "Ching (Cymbals)", ppl_code: "CHI", active: true},
  {description: "Chekere", ppl_code: "CHK", active: true},
  {description: "Chimes", ppl_code: "CHM", active: true},
  {description: "Chapman Stick", ppl_code: "CHS", active: true},
  {description: "Chanting", ppl_code: "CHT", active: true},
  {description: "Cimpoi", ppl_code: "CIM", active: true},
  {description: "Citole", ppl_code: "CIT", active: true},
  {description: "Caja", ppl_code: "CJA", active: true},
  {description: "Caj n", ppl_code: "CJN", active: true},
  {description: "Clarinet", ppl_code: "CLA", active: true},
  {description: "Clarinet (C)", ppl_code: "CLC", active: true},
  {description: "Clarinet (E Flat)", ppl_code: "CLE", active: true},
  {description: "Chocalho", ppl_code: "CLH", active: true},
  {description: "Chalumeau", ppl_code: "CLM", active: true},
  {description: "Clapping", ppl_code: "CLP", active: true},
  {description: "Clarsach", ppl_code: "CLR", active: true},
  {description: "Claves", ppl_code: "CLS", active: true},
  {description: "Clavier", ppl_code: "CLV", active: true},
  {description: "Comedian", ppl_code: "CMD", active: true},
  {description: "Choirmaster", ppl_code: "CMR", active: true},
  {description: "C Melody Saxophone", ppl_code: "CMS", active: true},
  {description: "Commentator", ppl_code: "CMT", active: true},
  {description: "Chinese Flute", ppl_code: "CNF", active: true},
  {description: "Cinema Organ", ppl_code: "CNO", active: true},
  {description: "Cantor", ppl_code: "CNR", active: true},
  {description: "Contralto (voice)", ppl_code: "CNT", active: true},
  {description: "Congas", ppl_code: "COA", active: true},
  {description: "Comb", ppl_code: "COB", active: true},
  {description: "Conductor (Instruments)", ppl_code: "COI", active: true},
  {description: "Conductor", ppl_code: "CON", active: true},
  {description: "Congos", ppl_code: "COO", active: true},
  {description: "Conductor (Strings)", ppl_code: "COS", active: true},
  {description: "Conductor (Vocals)", ppl_code: "COV", active: true},
  {description: "Cowbell", ppl_code: "COW", active: true},
  {description: "Calliope", ppl_code: "CPE", active: true},
  {description: "Chap Lek", ppl_code: "CPL", active: true},
  {description: "Clappers", ppl_code: "CPS", active: true},
  {description: "Carillon", ppl_code: "CRL", active: true},
  {description: "Crumhorn", ppl_code: "CRM", active: true},
  {description: "Cornet", ppl_code: "CRN", active: true},
  {description: "Concertina", ppl_code: "CRT", active: true},
  {description: "Crwth", ppl_code: "CRW", active: true},
  {description: "Colascione", ppl_code: "CSC", active: true},
  {description: "Conch Shell", ppl_code: "CSH", active: true},
  {description: "Chansonnier", ppl_code: "CSN", active: true},
  {description: "Celeste", ppl_code: "CST", active: true},
  {description: "Contrabass Saxophone", ppl_code: "CSX", active: true},
  {description: "Contrabass Clarinet", ppl_code: "CTC", active: true},
  {description: "Crotales", ppl_code: "CTL", active: true},
  {description: "Counter-Tenor (voice)", ppl_code: "CTN", active: true},
  {description: "Cornett", ppl_code: "CTO", active: true},
  {description: "Chitarrone", ppl_code: "CTR", active: true},
  {description: "Cittern", ppl_code: "CTT", active: true},
  {description: "Cuatro", ppl_code: "CUA", active: true},
  {description: "Cuica", ppl_code: "CUI", active: true},
  {description: "Curtal", ppl_code: "CUR", active: true},
  {description: "Cavaco", ppl_code: "CVA", active: true},
  {description: "Clavichord", ppl_code: "CVC", active: true},
  {description: "Clavinet", ppl_code: "CVT", active: true},
  {description: "Chiwata", ppl_code: "CWT", active: true},
  {description: "Caixa", ppl_code: "CXA", active: true},
  {description: "Caxixi", ppl_code: "CXI", active: true},
  {description: "Cymbals", ppl_code: "CYM", active: true},
  {description: "DJ", ppl_code: "D_J", active: true},
  {description: "Daf", ppl_code: "DAF", active: true},
  {description: "Daire", ppl_code: "DAI", active: true},
  {description: "Dan Tranh", ppl_code: "DAT", active: true},
  {description: "Damaru", ppl_code: "DAU", active: true},
  {description: "Daxaphone", ppl_code: "DAX", active: true},
  {description: "Dobro-Bass", ppl_code: "DBA", active: true},
  {description: "Double Bass", ppl_code: "DBB", active: true},
  {description: "Doumbi", ppl_code: "DBI", active: true},
  {description: "Dumbelek", ppl_code: "DBK", active: true},
  {description: "Double Bassoon", ppl_code: "DBS", active: true},
  {description: "Dan Bau", ppl_code: "DBU", active: true},
  {description: "Dulceola", ppl_code: "DCL", active: true},
  {description: "Dulcian", ppl_code: "DCN", active: true},
  {description: "Double Clarinet", ppl_code: "DCT", active: true},
  {description: "Dundun", ppl_code: "DDN", active: true},
  {description: "Def", ppl_code: "DEF", active: true},
  {description: "Diaff", ppl_code: "DFF", active: true},
  {description: "Double Flute", ppl_code: "DFL", active: true},
  {description: "Dholak", ppl_code: "DHK", active: true},
  {description: "Dhol", ppl_code: "DHL", active: true},
  {description: "Di?", ppl_code: "DI_", active: true},
  {description: "Dilruba", ppl_code: "DIB", active: true},
  {description: "Didjeridu", ppl_code: "DID", active: true},
  {description: "Di (Flute)", ppl_code: "DIF", active: true},
  {description: "Director (Musical)", ppl_code: "DIR", active: true},
  {description: "Di ( Slit Drum)", ppl_code: "DIS", active: true},
  {description: "Dizi", ppl_code: "DIZ", active: true},
  {description: "Djembe", ppl_code: "DJM", active: true},
  {description: "Dj (Spoken Word)", ppl_code: "DJS", active: true},
  {description: "Djura", ppl_code: "DJU", active: true},
  {description: "Droma", ppl_code: "DMA", active: true},
  {description: "Drum Major", ppl_code: "DMJ", active: true},
  {description: "Drum Machine", ppl_code: "DMM", active: true},
  {description: "Danburo", ppl_code: "DNB", active: true},
  {description: "Dan Nguyet", ppl_code: "DNG", active: true},
  {description: "Doneli", ppl_code: "DNL", active: true},
  {description: "Dobro", ppl_code: "DOB", active: true},
  {description: "Dohol", ppl_code: "DOH", active: true},
  {description: "Doira", ppl_code: "DOI", active: true},
  {description: "Dombra", ppl_code: "DOM", active: true},
  {description: "Donno", ppl_code: "DON", active: true},
  {description: "Doumbaki", ppl_code: "DOU", active: true},
  {description: "Diple", ppl_code: "DPL", active: true},
  {description: "Drum Programmer", ppl_code: "DPR", active: true},
  {description: "Dotara", ppl_code: "DRA", active: true},
  {description: "Darabukka", ppl_code: "DRB", active: true},
  {description: "Dril-Bu", ppl_code: "DRI", active: true},
  {description: "Drum", ppl_code: "DRM", active: true},
  {description: "Drums", ppl_code: "DRU", active: true},
  {description: "Drum Sergeant", ppl_code: "DSG", active: true},
  {description: "Dilli Tuiduk", ppl_code: "DTD", active: true},
  {description: "Duduk", ppl_code: "DUD", active: true},
  {description: "Duff", ppl_code: "DUF", active: true},
  {description: "Duggi", ppl_code: "DUG", active: true},
  {description: "Dulcimer", ppl_code: "DUL", active: true},
  {description: "Dumbuks", ppl_code: "DUM", active: true},
  {description: "Dung-Chen", ppl_code: "DUN", active: true},
  {description: "Dutar", ppl_code: "DUT", active: true},
  {description: "Dvojnice", ppl_code: "DVJ", active: true},
  {description: "Davul", ppl_code: "DVL", active: true},
  {description: "Electric Accordion", ppl_code: "EAC", active: true},
  {description: "Electric Appalachian Dulcimer", ppl_code: "EAD", active: true},
  {description: "Electric Baritone Guitar", ppl_code: "EBA", active: true},
  {description: "Electric Bass Guitar", ppl_code: "EBG", active: true},
  {description: "Electronic Cello", ppl_code: "ECE", active: true},
  {description: "Electronic Drums", ppl_code: "EDS", active: true},
  {description: "Electric Fiddle", ppl_code: "EFI", active: true},
  {description: "Sound Effects", ppl_code: "EFX", active: true},
  {description: "Electric Guitar", ppl_code: "EGT", active: true},
  {description: "English Guitar", ppl_code: "EGU", active: true},
  {description: "Electric Harp", ppl_code: "EHR", active: true},
  {description: "Electric Keyboard", ppl_code: "EKB", active: true},
  {description: "Ektar", ppl_code: "EKT", active: true},
  {description: "Electronics", ppl_code: "ELE", active: true},
  {description: "Electronium", ppl_code: "ELN", active: true},
  {description: "Emulator", ppl_code: "EMU", active: true},
  {description: "English Bagpipes", ppl_code: "ENB", active: true},
  {description: "English Concertina", ppl_code: "ENC", active: true},
  {description: "English Horn", ppl_code: "ENH", active: true},
  {description: "Electronic Organ", ppl_code: "ENO", active: true},
  {description: "Electric Organ", ppl_code: "EOR", active: true},
  {description: "Electronic Percussion", ppl_code: "EPE", active: true},
  {description: "Electronic Piano", ppl_code: "EPF", active: true},
  {description: "Electric Piano", ppl_code: "EPI", active: true},
  {description: "Erhu", ppl_code: "ERH", active: true},
  {description: "Esraj", ppl_code: "ESR", active: true},
  {description: "Electric Sitar", ppl_code: "EST", active: true},
  {description: "Electric Upright Bass", ppl_code: "EUB", active: true},
  {description: "Euphonium", ppl_code: "EUP", active: true},
  {description: "Electric Viola", ppl_code: "EVA", active: true},
  {description: "Electronic Vibraphone", ppl_code: "EVB", active: true},
  {description: "Electric Cello", ppl_code: "EVC", active: true},
  {description: "Electric Violin", ppl_code: "EVI", active: true},
  {description: "Electronic Violin", ppl_code: "EVN", active: true},
  {description: "Electronic Wind Instrument", ppl_code: "EWI", active: true},
  {description: "Fretless Bass Guitar", ppl_code: "FBG", active: true},
  {description: "Frame Drum", ppl_code: "FDM", active: true},
  {description: "Feedback", ppl_code: "FEE", active: true},
  {description: "FanfareTrumpet", ppl_code: "FFT", active: true},
  {description: "Fairground Organ", ppl_code: "FGO", active: true},
  {description: "Fretless Guitar", ppl_code: "FGT", active: true},
  {description: "Fiddle", ppl_code: "FID", active: true},
  {description: "Fife", ppl_code: "FIF", active: true},
  {description: "Flageolet", ppl_code: "FLG", active: true},
  {description: "Flugelhorn", ppl_code: "FLH", active: true},
  {description: "Flute Organ", ppl_code: "FLO", active: true},
  {description: "Falsetto (voice)", ppl_code: "FLS", active: true},
  {description: "Flute", ppl_code: "FLU", active: true},
  {description: "Flexatone", ppl_code: "FLX", active: true},
  {description: "Finger Cymbals", ppl_code: "FNC", active: true},
  {description: "Finger Clicks", ppl_code: "FNL", active: true},
  {description: "Folklorist", ppl_code: "FOL", active: true},
  {description: "Fotdella", ppl_code: "FOT", active: true},
  {description: "French Bagpipes", ppl_code: "FRB", active: true},
  {description: "French Horn", ppl_code: "FRH", active: true},
  {description: "Five String Banjo", ppl_code: "FSB", active: true},
  {description: "Foot Stamping", ppl_code: "FST", active: true},
  {description: "Foot Tapping", ppl_code: "FTA", active: true},
  {description: "Fortepiano", ppl_code: "FTP", active: true},
  {description: "Fujara", ppl_code: "FUJ", active: true},
  {description: "Fyell", ppl_code: "FYE", active: true},
  {description: "Floyera", ppl_code: "FYR", active: true},
  {description: "Gadulka", ppl_code: "GAD", active: true},
  {description: "Gajde", ppl_code: "GAJ", active: true},
  {description: "Galo", ppl_code: "GAL", active: true},
  {description: "Gamelan", ppl_code: "GAM", active: true},
  {description: "Ganga", ppl_code: "GAN", active: true},
  {description: "Gardon", ppl_code: "GAR", active: true},
  {description: "Gbedu", ppl_code: "GBD", active: true},
  {description: "Gambang", ppl_code: "GBN", active: true},
  {description: "Gua'chara", ppl_code: "GCA", active: true},
  {description: "Gorodao", ppl_code: "GDO", active: true},
  {description: "Genggong", ppl_code: "GEN", active: true},
  {description: "Goofus", ppl_code: "GFS", active: true},
  {description: "Goge", ppl_code: "GGE", active: true},
  {description: "Gangsa", ppl_code: "GGS", active: true},
  {description: "Ghatam", ppl_code: "GHA", active: true},
  {description: "Ghati", ppl_code: "GHI", active: true},
  {description: "Ghara", ppl_code: "GHR", active: true},
  {description: "Ghayta", ppl_code: "GHT", active: true},
  {description: "Gaohu", ppl_code: "GHU", active: true},
  {description: "Gimbri", ppl_code: "GIM", active: true},
  {description: "Gini", ppl_code: "GIN", active: true},
  {description: "Gittern", ppl_code: "GIT", active: true},
  {description: "Gankogui", ppl_code: "GKG", active: true},
  {description: "Glockenspiel", ppl_code: "GKS", active: true},
  {description: "Glass Harmonica", ppl_code: "GLH", active: true},
  {description: "Gunje", ppl_code: "GNJ", active: true},
  {description: "Gender", ppl_code: "GNR", active: true},
  {description: "Gong", ppl_code: "GON", active: true},
  {description: "Gourd Rattle", ppl_code: "GRD", active: true},
  {description: "Grantang", ppl_code: "GRG", active: true},
  {description: "Griot", ppl_code: "GRI", active: true},
  {description: "Grneta", ppl_code: "GRN", active: true},
  {description: "Guntang", ppl_code: "GTG", active: true},
  {description: "Guitsteel", ppl_code: "GTL", active: true},
  {description: "Guitarron", ppl_code: "GTN", active: true},
  {description: "Guitar", ppl_code: "GTR", active: true},
  {description: "Guitar Synthesizer", ppl_code: "GTS", active: true},
  {description: "Gu", ppl_code: "GU_", active: true},
  {description: "Guayo", ppl_code: "GUA", active: true},
  {description: "Gubgubi", ppl_code: "GUB", active: true},
  {description: "Gudugudu", ppl_code: "GUD", active: true},
  {description: "Gung", ppl_code: "GUG", active: true},
  {description: "Guiro", ppl_code: "GUI", active: true},
  {description: "Guan", ppl_code: "GUN", active: true},
  {description: "Guitarra", ppl_code: "GUR", active: true},
  {description: "Ganza", ppl_code: "GZA", active: true},
  {description: "Hammered Dulcimer", ppl_code: "HAD", active: true},
  {description: "Hawaiian Guitar", ppl_code: "HAG", active: true},
  {description: "Hammer", ppl_code: "HAM", active: true},
  {description: "Hammond Organ", ppl_code: "HAO", active: true},
  {description: "Harp", ppl_code: "HAR", active: true},
  {description: "Hand Bells", ppl_code: "HBE", active: true},
  {description: "Hudukka", ppl_code: "HDK", active: true},
  {description: "Hot Fountain Pen", ppl_code: "HFP", active: true},
  {description: "Harp Guitar", ppl_code: "HGT", active: true},
  {description: "Hunting Horn (Valved)", ppl_code: "HHN", active: true},
  {description: "Hi-Hat", ppl_code: "HHT", active: true},
  {description: "Heckelphone", ppl_code: "HKP", active: true},
  {description: "Helicon", ppl_code: "HLC", active: true},
  {description: "Humming", ppl_code: "HMM", active: true},
  {description: "Harmonium", ppl_code: "HMN", active: true},
  {description: "Hoddu", ppl_code: "HOD", active: true},
  {description: "Horn", ppl_code: "HOR", active: true},
  {description: "Hosho", ppl_code: "HOS", active: true},
  {description: "Highland Bagpipes", ppl_code: "HPI", active: true},
  {description: "Harpsipiano", ppl_code: "HPN", active: true},
  {description: "Hardanger Fiddle", ppl_code: "HRD", active: true},
  {description: "Harmonica", ppl_code: "HRM", active: true},
  {description: "Horn", ppl_code: "HRN", active: true},
  {description: "Harpsichord", ppl_code: "HRP", active: true},
  {description: "Haute-Contre (voice)", ppl_code: "HTC", active: true},
  {description: "Huapanguera", ppl_code: "HUA", active: true},
  {description: "Hurdy Gurdy", ppl_code: "HUR", active: true},
  {description: "Imitation Bass", ppl_code: "IMB", active: true},
  {description: "Indian Harp", ppl_code: "INH", active: true},
  {description: "Instruments", ppl_code: "INS", active: true},
  {description: "Impersonator", ppl_code: "IPE", active: true},
  {description: "Irish Harp", ppl_code: "IRH", active: true},
  {description: "Interviewee", ppl_code: "IVE", active: true},
  {description: "Interviewer", ppl_code: "IVR", active: true},
  {description: "Jarana", ppl_code: "JAR", active: true},
  {description: "Jagd Horn", ppl_code: "JDH", active: true},
  {description: "Jegogan", ppl_code: "JGG", active: true},
  {description: "Jejo", ppl_code: "JJO", active: true},
  {description: "Jejo Voatavo", ppl_code: "JJV", active: true},
  {description: "Jumbush", ppl_code: "JMB", active: true},
  {description: "Joze", ppl_code: "JOZ", active: true},
  {description: "Jublag", ppl_code: "JUB", active: true},
  {description: "Jug", ppl_code: "JUG", active: true},
  {description: "Jushichigen-Kin (Bass Koto)", ppl_code: "JUK", active: true},
  {description: "Jawan", ppl_code: "JWA", active: true},
  {description: "Japanese Wooden Flute", ppl_code: "JWF", active: true},
  {description: "Jews Harp", ppl_code: "JWH", active: true},
  {description: "Jazz-Horn", ppl_code: "JZH", active: true},
  {description: "Kacapi", ppl_code: "KAC", active: true},
  {description: "Kalimba", ppl_code: "KAL", active: true},
  {description: "Kamanche", ppl_code: "KAM", active: true},
  {description: "Kantele", ppl_code: "KAN", active: true},
  {description: "Karna (Trumpet)", ppl_code: "KAR", active: true},
  {description: "Kaval", ppl_code: "KAV", active: true},
  {description: "Kayagum", ppl_code: "KAY", active: true},
  {description: "Kazoo", ppl_code: "KAZ", active: true},
  {description: "Kabosa", ppl_code: "KBS", active: true},
  {description: "Kelenang", ppl_code: "KEL", active: true},
  {description: "Kemence", ppl_code: "KEM", active: true},
  {description: "Kena", ppl_code: "KEN", active: true},
  {description: "Keyboards", ppl_code: "KEY", active: true},
  {description: "Kaba Gaida", ppl_code: "KGD", active: true},
  {description: "Komun'go", ppl_code: "KGO", active: true},
  {description: "Khaen", ppl_code: "KHA", active: true},
  {description: "Khalam", ppl_code: "KHL", active: true},
  {description: "Khol", ppl_code: "KHO", active: true},
  {description: "Khuur", ppl_code: "KHU", active: true},
  {description: "Khulsan Khuur", ppl_code: "KKH", active: true},
  {description: "Kkwaengwari", ppl_code: "KKW", active: true},
  {description: "Klong Khaek", ppl_code: "KLK", active: true},
  {description: "Kelenang", ppl_code: "KLN", active: true},
  {description: "Klong", ppl_code: "KLO", active: true},
  {description: "Kamaica", ppl_code: "KMA", active: true},
  {description: "Kamac", ppl_code: "KMC", active: true},
  {description: "Kemene", ppl_code: "KMN", active: true},
  {description: "Kempul", ppl_code: "KMP", active: true},
  {description: "Kendang", ppl_code: "KND", active: true},
  {description: "Kanjira", ppl_code: "KNJ", active: true},
  {description: "Kenong", ppl_code: "KOG", active: true},
  {description: "Kora", ppl_code: "KOR", active: true},
  {description: "Koto", ppl_code: "KOT", active: true},
  {description: "Kempur", ppl_code: "KPR", active: true},
  {description: "Kra", ppl_code: "KRA", active: true},
  {description: "Karigo", ppl_code: "KRI", active: true},
  {description: "Kaiamba Rambo", ppl_code: "KRM", active: true},
  {description: "Krar", ppl_code: "KRR", active: true},
  {description: "Karamouza", ppl_code: "KRZ", active: true},
  {description: "Kusle", ppl_code: "KSL", active: true},
  {description: "Kortholt", ppl_code: "KTH", active: true},
  {description: "Ketuk", ppl_code: "KTK", active: true},
  {description: "Kartal", ppl_code: "KTL", active: true},
  {description: "Korintsana", ppl_code: "KTS", active: true},
  {description: "Kong Wong Yai", ppl_code: "KWY", active: true},
  {description: "Kenyir", ppl_code: "KYI", active: true},
  {description: "Lakota Flute", ppl_code: "LAF", active: true},
  {description: "Laouto", ppl_code: "LAO", active: true},
  {description: "Laud", ppl_code: "LAU", active: true},
  {description: "Lamba", ppl_code: "LBA", active: true},
  {description: "Launeddas", ppl_code: "LDS", active: true},
  {description: "Leader", ppl_code: "LEA", active: true},
  {description: "Log Drum", ppl_code: "LGD", active: true},
  {description: "Lute-Harpsichord", ppl_code: "LHC", active: true},
  {description: "Lilting", ppl_code: "LIL", active: true},
  {description: "Limbe", ppl_code: "LIM", active: true},
  {description: "Lira Organizzatai", ppl_code: "LIO", active: true},
  {description: "Lokanga Bara", ppl_code: "LKB", active: true},
  {description: "Lamellaphone", ppl_code: "LLL", active: true},
  {description: "Lowland Pipes", ppl_code: "LLP", active: true},
  {description: "Llaute", ppl_code: "LLT", active: true},
  {description: "Lokole", ppl_code: "LOK", active: true},
  {description: "Lirica", ppl_code: "LRC", active: true},
  {description: "Lyre", ppl_code: "LRE", active: true},
  {description: "Lirone", ppl_code: "LRO", active: true},
  {description: "Lap Steel Guitar", ppl_code: "LSG", active: true},
  {description: "Lukeme", ppl_code: "LUK", active: true},
  {description: "Lute", ppl_code: "LUT", active: true},
  {description: "Lyra Viol", ppl_code: "LVL", active: true},
  {description: "Low Whistle", ppl_code: "LWH", active: true},
  {description: "Lyra", ppl_code: "LYA", active: true},
  {description: "Lyricon", ppl_code: "LYR", active: true},
  {description: "Lysarden", ppl_code: "LYS", active: true},
  {description: "MC", ppl_code: "M_C", active: true},
  {description: "Mandolin", ppl_code: "MAN", active: true},
  {description: "Marimba", ppl_code: "MAR", active: true},
  {description: "Mbira", ppl_code: "MBA", active: true},
  {description: "Mouth Bow", ppl_code: "MBW", active: true},
  {description: "Murcang", ppl_code: "MCG", active: true},
  {description: "Mandola", ppl_code: "MDA", active: true},
  {description: "Mandocello", ppl_code: "MDC", active: true},
  {description: "Maddalam ", ppl_code: "MDD", active: true},
  {description: "Madal", ppl_code: "MDL", active: true},
  {description: "Music Director", ppl_code: "MDR", active: true},
  {description: "Musical Director (Shows)", ppl_code: "MDS", active: true},
  {description: "Mejoranera", ppl_code: "MEJ", active: true},
  {description: "Melodeon", ppl_code: "MEL", active: true},
  {description: "Mey", ppl_code: "MEY", active: true},
  {description: "Magruna", ppl_code: "MGR", active: true},
  {description: "Midistick", ppl_code: "MID", active: true},
  {description: "Minister", ppl_code: "MIN", active: true},
  {description: "Miscellaneous", ppl_code: "MIS", active: true},
  {description: "Mizmar", ppl_code: "MIZ", active: true},
  {description: "Manjira", ppl_code: "MJR", active: true},
  {description: "Manjur", ppl_code: "MJU", active: true},
  {description: "Morin Khuur", ppl_code: "MKH", active: true},
  {description: "Melodica", ppl_code: "MLD", active: true},
  {description: "Mellophonium", ppl_code: "MLM", active: true},
  {description: "Mellotron", ppl_code: "MLN", active: true},
  {description: "Mellophone", ppl_code: "MLP", active: true},
  {description: "Mouth Music", ppl_code: "MMU", active: true},
  {description: "Mong", ppl_code: "MNG", active: true},
  {description: "Mandore", ppl_code: "MOR", active: true},
  {description: "Maracas", ppl_code: "MRC", active: true},
  {description: "Mrdanga", ppl_code: "MRD", active: true},
  {description: "Mouth Organ", ppl_code: "MRG", active: true},
  {description: "Marimbula", ppl_code: "MRM", active: true},
  {description: "Morrisette", ppl_code: "MRT", active: true},
  {description: "Marovany", ppl_code: "MRV", active: true},
  {description: "Mirwas", ppl_code: "MRW", active: true},
  {description: "Masenqo", ppl_code: "MSQ", active: true},
  {description: "Muselar", ppl_code: "MSR", active: true},
  {description: "Musette", ppl_code: "MST", active: true},
  {description: "Metallophone", ppl_code: "MTP", active: true},
  {description: "Murali", ppl_code: "MUR", active: true},
  {description: "Mezzo-Contralto (voice)", ppl_code: "MZC", active: true},
  {description: "Manzello", ppl_code: "MZL", active: true},
  {description: "Mezzo-Soprano (voice)", ppl_code: "MZS", active: true},
  {description: "Nakers", ppl_code: "NAK", active: true},
  {description: "Nal (Drum)", ppl_code: "NAL", active: true},
  {description: "Nao", ppl_code: "NAO", active: true},
  {description: "Naqqara", ppl_code: "NAQ", active: true},
  {description: "Narrator", ppl_code: "NAR", active: true},
  {description: "Nay", ppl_code: "NAY", active: true},
  {description: "Nose Flute", ppl_code: "NFL", active: true},
  {description: "Ngomi", ppl_code: "NGM", active: true},
  {description: "Ngoma", ppl_code: "NGO", active: true},
  {description: "Nagasvaram", ppl_code: "NGV", active: true},
  {description: "Natural Horn", ppl_code: "NHN", active: true},
  {description: "Njarka", ppl_code: "NJA", active: true},
  {description: "Nkoni", ppl_code: "NKO", active: true},
  {description: "Nanga", ppl_code: "NNG", active: true},
  {description: "Northumbrian Small Pipes", ppl_code: "NSP", active: true},
  {description: "Natural Trumpet", ppl_code: "NTP", active: true},
  {description: "Nattuva Talam", ppl_code: "NTT", active: true},
  {description: "Novachord", ppl_code: "NVC", active: true},
  {description: "Nyckelharpa", ppl_code: "NYC", active: true},
  {description: "Nyatiti", ppl_code: "NYT", active: true},
  {description: "Oboe D'Amore", ppl_code: "OBD", active: true},
  {description: "Oboe", ppl_code: "OBO", active: true},
  {description: "Ocarina", ppl_code: "OCA", active: true},
  {description: "Oboe DaCaccia", ppl_code: "ODC", active: true},
  {description: "Ondes Martenot", ppl_code: "ODM", active: true},
  {description: "Okonkole", ppl_code: "OKK", active: true},
  {description: "One-Man Band", ppl_code: "OMB", active: true},
  {description: "Omnichord", ppl_code: "OMN", active: true},
  {description: "Ondioline", ppl_code: "OND", active: true},
  {description: "Optigan", ppl_code: "OPG", active: true},
  {description: "Ophicleide", ppl_code: "OPH", active: true},
  {description: "Organ", ppl_code: "ORG", active: true},
  {description: "Orpharion", ppl_code: "ORP", active: true},
  {description: "Pedabro", ppl_code: "PAB", active: true},
  {description: "Pakhavaj", ppl_code: "PAK", active: true},
  {description: "Pano", ppl_code: "PAN", active: true},
  {description: "Pipe And Tabor", ppl_code: "PAT", active: true},
  {description: "Piccolo Bass Guitar", ppl_code: "PBG", active: true},
  {description: "Pi Chawa", ppl_code: "PCH", active: true},
  {description: "Piccolo Trumpet", ppl_code: "PCT", active: true},
  {description: "Pandeiro", ppl_code: "PDO", active: true},
  {description: "Pandereta", ppl_code: "PDT", active: true},
  {description: "Pardessus DeViole", ppl_code: "PDV", active: true},
  {description: "Percussion", ppl_code: "PER", active: true},
  {description: "Post Horn", ppl_code: "PHN", active: true},
  {description: "Piano", ppl_code: "PIA", active: true},
  {description: "Piccolo", ppl_code: "PIC", active: true},
  {description: "Piffaro", ppl_code: "PIF", active: true},
  {description: "Piano Accordion", ppl_code: "PIN", active: true},
  {description: "Pipes", ppl_code: "PIP", active: true},
  {description: "P'iri", ppl_code: "PIR", active: true},
  {description: "Pujador", ppl_code: "PJD", active: true},
  {description: "Pocket Trumpet", ppl_code: "PKT", active: true},
  {description: "Pulankulal", ppl_code: "PLK", active: true},
  {description: "Player Piano", ppl_code: "PLP", active: true},
  {description: "Pipe Major", ppl_code: "PMA", active: true},
  {description: "Palmas", ppl_code: "PMS", active: true},
  {description: "Pi Nai", ppl_code: "PNA", active: true},
  {description: "Poetry Reader", ppl_code: "POE", active: true},
  {description: "Pipe", ppl_code: "PPE", active: true},
  {description: "Polyphon", ppl_code: "PPN", active: true},
  {description: "Panpipes", ppl_code: "PPP", active: true},
  {description: "Eligible Studio Producer", ppl_code: "PPR", active: true},
  {description: "Pipe Sergeant", ppl_code: "PPS", active: true},
  {description: "Preacher", ppl_code: "PRE", active: true},
  {description: "Programmer", ppl_code: "PRG", active: true},
  {description: "Presenter", ppl_code: "PRT", active: true},
  {description: "Psaltery", ppl_code: "PSA", active: true},
  {description: "Pedal Steel Guitar", ppl_code: "PSG", active: true},
  {description: "Positive (Organ)", ppl_code: "PTV", active: true},
  {description: "Qanun", ppl_code: "QAN", active: true},
  {description: "Quintfagott", ppl_code: "QFG", active: true},
  {description: "Qirba", ppl_code: "QIR", active: true},
  {description: "Quinton", ppl_code: "QNT", active: true},
  {description: "Qasaba", ppl_code: "QSB", active: true},
  {description: "Quills", ppl_code: "QUL", active: true},
  {description: "Quinto", ppl_code: "QUT", active: true},
  {description: "Rabab", ppl_code: "RAB", active: true},
  {description: "Raconteur", ppl_code: "RAC", active: true},
  {description: "Rauschpfeife", ppl_code: "RAU", active: true},
  {description: "Rababa", ppl_code: "RBB", active: true},
  {description: "Rubboard", ppl_code: "RBD", active: true},
  {description: "Rabel", ppl_code: "RBL", active: true},
  {description: "Racket", ppl_code: "RCK", active: true},
  {description: "Reciter", ppl_code: "RCR", active: true},
  {description: "Rondadores", ppl_code: "RDD", active: true},
  {description: "Rag Dung", ppl_code: "RDG", active: true},
  {description: "Reeds", ppl_code: "RDS", active: true},
  {description: "Rebec", ppl_code: "REB", active: true},
  {description: "Recorder", ppl_code: "REC", active: true},
  {description: "Reporter", ppl_code: "REP", active: true},
  {description: "Regals", ppl_code: "RGL", active: true},
  {description: "Rgya-Gling", ppl_code: "RGY", active: true},
  {description: "Rkang-Gling", ppl_code: "RKG", active: true},
  {description: "Rol-Mo", ppl_code: "RLM", active: true},
  {description: "Ranat Ek", ppl_code: "RNE", active: true},
  {description: "Rnga", ppl_code: "RNG", active: true},
  {description: "Studio Personnel (Performing)", ppl_code: "RNP", active: true},
  {description: "Ranat Thum", ppl_code: "RNT", active: true},
  {description: "Repicador", ppl_code: "RPC", active: true},
  {description: "Repique", ppl_code: "RPQ", active: true},
  {description: "Rapper", ppl_code: "RPR", active: true},
  {description: "RIQQ", ppl_code: "RQQ", active: true},
  {description: "Requinto", ppl_code: "RQT", active: true},
  {description: "Reco-Reco", ppl_code: "RRC", active: true},
  {description: "Rain Stick", ppl_code: "RST", active: true},
  {description: "Rattle", ppl_code: "RTT", active: true},
  {description: "Ruann", ppl_code: "RUA", active: true},
  {description: "RudraVina", ppl_code: "RUD", active: true},
  {description: "Reyong", ppl_code: "RYO", active: true},
  {description: "Sabaro", ppl_code: "SAB", active: true},
  {description: "Sahnai", ppl_code: "SAH", active: true},
  {description: "Sal", ppl_code: "SAL", active: true},
  {description: "Sampler", ppl_code: "SAM", active: true},
  {description: "Sao", ppl_code: "SAO", active: true},
  {description: "Sampled Performer", ppl_code: "SAP", active: true},
  {description: "Sarrusophone", ppl_code: "SAR", active: true},
  {description: "Satara", ppl_code: "SAT", active: true},
  {description: "Saw", ppl_code: "SAW", active: true},
  {description: "Saxophone", ppl_code: "SAX", active: true},
  {description: "Saz", ppl_code: "SAZ", active: true},
  {description: "Shinobue", ppl_code: "SBU", active: true},
  {description: "Sackbut", ppl_code: "SCK", active: true},
  {description: "Sopranino Clarinet", ppl_code: "SCL", active: true},
  {description: "Soprano Crumhorn", ppl_code: "SCM", active: true},
  {description: "Scraper", ppl_code: "SCR", active: true},
  {description: "Dj (Scratcher)", ppl_code: "SCT", active: true},
  {description: "Sodinar", ppl_code: "SDA", active: true},
  {description: "Snare Drum", ppl_code: "SDM", active: true},
  {description: "Steel Drum", ppl_code: "SDR", active: true},
  {description: "Sekere", ppl_code: "SEK", active: true},
  {description: "Serpent", ppl_code: "SER", active: true},
  {description: "Steel Guitar", ppl_code: "SGT", active: true},
  {description: "Shudraga", ppl_code: "SHD", active: true},
  {description: "Sheng", ppl_code: "SHE", active: true},
  {description: "Shofar", ppl_code: "SHF", active: true},
  {description: "Shakuhachi", ppl_code: "SHH", active: true},
  {description: "Shaker", ppl_code: "SHK", active: true},
  {description: "Shamisen", ppl_code: "SHM", active: true},
  {description: "Shenai", ppl_code: "SHN", active: true},
  {description: "Shouting", ppl_code: "SHO", active: true},
  {description: "Shuttle Pipes", ppl_code: "SHP", active: true},
  {description: "Sihu", ppl_code: "SIH", active: true},
  {description: "Sil-Snyan", ppl_code: "SIL", active: true},
  {description: "Siren", ppl_code: "SIR", active: true},
  {description: "Sopranino Saxophone", ppl_code: "SIS", active: true},
  {description: "Sign Language Interpreter", ppl_code: "SLI", active: true},
  {description: "Sopilka", ppl_code: "SLK", active: true},
  {description: "Slentem", ppl_code: "SLM", active: true},
  {description: "Saxello", ppl_code: "SLO", active: true},
  {description: "Steam Locomotive Sounds", ppl_code: "SLS", active: true},
  {description: "Salterio", ppl_code: "SLT", active: true},
  {description: "Surnai (Kashmir)", ppl_code: "SNA", active: true},
  {description: "Sanfona", ppl_code: "SNF", active: true},
  {description: "Santur", ppl_code: "SNT", active: true},
  {description: "Sanxian", ppl_code: "SNX", active: true},
  {description: "Souvliari", ppl_code: "SOL", active: true},
  {description: "Soprano (voice)", ppl_code: "SOP", active: true},
  {description: "Sousaphone", ppl_code: "SOU", active: true},
  {description: "Speech", ppl_code: "SPE", active: true},
  {description: "Square Pianoforte", ppl_code: "SPF", active: true},
  {description: "Spinet", ppl_code: "SPI", active: true},
  {description: "Spoons", ppl_code: "SPO", active: true},
  {description: "Spoken Word", ppl_code: "SPW", active: true},
  {description: "Sorna", ppl_code: "SRA", active: true},
  {description: "Surbahar", ppl_code: "SRB", active: true},
  {description: "Surdu", ppl_code: "SRD", active: true},
  {description: "Sopranino Recorder", ppl_code: "SRE", active: true},
  {description: "Sarod", ppl_code: "SRG", active: true},
  {description: "Sarangi", ppl_code: "SRN", active: true},
  {description: "Saron", ppl_code: "SRO", active: true},
  {description: "Saroz", ppl_code: "SRZ", active: true},
  {description: "Soprano Sax (C)", ppl_code: "SSC", active: true},
  {description: "Sindhi Sarangi", ppl_code: "SSG", active: true},
  {description: "Scottish Small Pipes", ppl_code: "SSP", active: true},
  {description: "Soprano Saxophone", ppl_code: "SSX", active: true},
  {description: "Setar", ppl_code: "STA", active: true},
  {description: "Step Dancer", ppl_code: "STE", active: true},
  {description: "Stritch", ppl_code: "STH", active: true},
  {description: "Storyteller", ppl_code: "STO", active: true},
  {description: "SlideTrumpet", ppl_code: "STP", active: true},
  {description: "Sitar", ppl_code: "STR", active: true},
  {description: "Stylophone", ppl_code: "STY", active: true},
  {description: "Suling", ppl_code: "SUL", active: true},
  {description: "Suona", ppl_code: "SUN", active: true},
  {description: "Surmandal", ppl_code: "SUR", active: true},
  {description: "Svirala", ppl_code: "SVR", active: true},
  {description: "Swanee Whistle", ppl_code: "SWH", active: true},
  {description: "Shawm", ppl_code: "SWM", active: true},
  {description: "Synthesizer", ppl_code: "SYN", active: true},
  {description: "Sanza", ppl_code: "SZA", active: true},
  {description: "Tabla", ppl_code: "TAB", active: true},
  {description: "Tar (Frame Drum)", ppl_code: "TAF", active: true},
  {description: "Taiko", ppl_code: "TAI", active: true},
  {description: "Tal", ppl_code: "TAL", active: true},
  {description: "Tambura", ppl_code: "TAM", active: true},
  {description: "Tar", ppl_code: "TAR", active: true},
  {description: "Tambur (Drum)", ppl_code: "TAU", active: true},
  {description: "Tavil", ppl_code: "TAV", active: true},
  {description: "Tabal", ppl_code: "TBA", active: true},
  {description: "Tubular Bells", ppl_code: "TBB", active: true},
  {description: "Timbales", ppl_code: "TBL", active: true},
  {description: "Tambora", ppl_code: "TBO", active: true},
  {description: "Tambourine", ppl_code: "TBR", active: true},
  {description: "Toumbas", ppl_code: "TBS", active: true},
  {description: "Tambur (Lute)", ppl_code: "TBU", active: true},
  {description: "Tibetan Bowls", ppl_code: "TBW", active: true},
  {description: "Tea Chest Bass", ppl_code: "TCB", active: true},
  {description: "Tap Dancer", ppl_code: "TDA", active: true},
  {description: "Talking Drum", ppl_code: "TDM", active: true},
  {description: "Tenor Banjo", ppl_code: "TEB", active: true},
  {description: "Trumpet (Eflat)", ppl_code: "TEF", active: true},
  {description: "Tenor Guitar", ppl_code: "TEG", active: true},
  {description: "Tenor", ppl_code: "TEN", active: true},
  {description: "Tenor Recorder", ppl_code: "TER", active: true},
  {description: "Tefi", ppl_code: "TFI", active: true},
  {description: "Treble Flute", ppl_code: "TFL", active: true},
  {description: "Triangle", ppl_code: "TGL", active: true},
  {description: "Taegum", ppl_code: "TGM", active: true},
  {description: "Twelve String Guitars", ppl_code: "TGT", active: true},
  {description: "Theorbo", ppl_code: "THB", active: true},
  {description: "Theatre Organ", ppl_code: "THO", active: true},
  {description: "Triple Harp", ppl_code: "THP", active: true},
  {description: "Theremin", ppl_code: "THR", active: true},
  {description: "Throat Singing", ppl_code: "THS", active: true},
  {description: "Timbal", ppl_code: "TIM", active: true},
  {description: "Tin Whistle", ppl_code: "TIN", active: true},
  {description: "Tiple", ppl_code: "TIP", active: true},
  {description: "Tepsija", ppl_code: "TJA", active: true},
  {description: "Tulum", ppl_code: "TLM", active: true},
  {description: "Tar (Flute)", ppl_code: "TLU", active: true},
  {description: "Tama", ppl_code: "TMA", active: true},
  {description: "Tombak", ppl_code: "TMB", active: true},
  {description: "Tamborim", ppl_code: "TMM", active: true},
  {description: "Timpani", ppl_code: "TMP", active: true},
  {description: "Tam Tam", ppl_code: "TMT", active: true},
  {description: "Tambur (Gong)", ppl_code: "TMU", active: true},
  {description: "Tanbura", ppl_code: "TNA", active: true},
  {description: "Tanbur", ppl_code: "TNB", active: true},
  {description: "Tenor Horn", ppl_code: "TNH", active: true},
  {description: "Trompeta", ppl_code: "TOA", active: true},
  {description: "Tiompan", ppl_code: "TOP", active: true},
  {description: "Tabor", ppl_code: "TOR", active: true},
  {description: "Traps", ppl_code: "TPA", active: true},
  {description: "Temple Block", ppl_code: "TPB", active: true},
  {description: "Tack Piano", ppl_code: "TPF", active: true},
  {description: "Tapan", ppl_code: "TPN", active: true},
  {description: "Tambura (South East Europe)", ppl_code: "TRA", active: true},
  {description: "Trompetica China", ppl_code: "TRC", active: true},
  {description: "Trumpet", ppl_code: "TRD", active: true},
  {description: "Treble (voice)", ppl_code: "TRE", active: true},
  {description: "Tarogato", ppl_code: "TRG", active: true},
  {description: "Trombone", ppl_code: "TRM", active: true},
  {description: "Tar Shenai", ppl_code: "TRN", active: true},
  {description: "Treble Recorder", ppl_code: "TRR", active: true},
  {description: "Tres", ppl_code: "TRS", active: true},
  {description: "Trumpet", ppl_code: "TRU", active: true},
  {description: "Tenor Sarrusophone", ppl_code: "TSA", active: true},
  {description: "Tenor Sordun", ppl_code: "TSD", active: true},
  {description: "Treble Shawm", ppl_code: "TSH", active: true},
  {description: "Dj (Toaster)", ppl_code: "TST", active: true},
  {description: "Tsugaru Samisen", ppl_code: "TSU", active: true},
  {description: "Tenor Saxophone", ppl_code: "TSX", active: true},
  {description: "Treble Tambura", ppl_code: "TTA", active: true},
  {description: "Tongtong", ppl_code: "TTG", active: true},
  {description: "Tom-Tom", ppl_code: "TTM", active: true},
  {description: "Tumba (Goblet Drum)", ppl_code: "TUA", active: true},
  {description: "Tuba", ppl_code: "TUB", active: true},
  {description: "Tumbadora", ppl_code: "TUM", active: true},
  {description: "Treble Viol", ppl_code: "TVI", active: true},
  {description: "Tenor Viol", ppl_code: "TVL", active: true},
  {description: "Tenor (voice)", ppl_code: "TVO", active: true},
  {description: "Txalaparta", ppl_code: "TXA", active: true},
  {description: "Toy Piano", ppl_code: "TYP", active: true},
  {description: "Tzouras", ppl_code: "TZO", active: true},
  {description: "Ud", ppl_code: "UDD", active: true},
  {description: "Udu", ppl_code: "UDU", active: true},
  {description: "Uilleann Pipes", ppl_code: "UIL", active: true},
  {description: "Ukulele", ppl_code: "UKE", active: true},
  {description: "Untuned Percussion", ppl_code: "UPE", active: true},
  {description: "Unidentified Payable Role", ppl_code: "UPR", active: true},
  {description: "Unidentified String Instument", ppl_code: "USI", active: true},
  {description: "Vibra-Slap", ppl_code: "VBR", active: true},
  {description: "Vocoder", ppl_code: "VCO", active: true},
  {description: "Violoncello Piccolo", ppl_code: "VCP", active: true},
  {description: "Viola D`Amore", ppl_code: "VDA", active: true},
  {description: "Viola DaGamba", ppl_code: "VDG", active: true},
  {description: "Vena", ppl_code: "VEN", active: true},
  {description: "Vocal Effects", ppl_code: "VFX", active: true},
  {description: "Virginals", ppl_code: "VGL", active: true},
  {description: "Viola (Guitar)", ppl_code: "VGT", active: true},
  {description: "Viola", ppl_code: "VIA", active: true},
  {description: "Vibraphone", ppl_code: "VIB", active: true},
  {description: "Vihuela", ppl_code: "VIH", active: true},
  {description: "Vina", ppl_code: "VIN", active: true},
  {description: "Violin", ppl_code: "VIO", active: true},
  {description: "Viola Bastarda", ppl_code: "VLB", active: true},
  {description: "Valiha", ppl_code: "VLH", active: true},
  {description: "Violarina", ppl_code: "VLR", active: true},
  {description: "Violone", ppl_code: "VNE", active: true},
  {description: "Violino Piccolo", ppl_code: "VNP", active: true},
  {description: "Vocals", ppl_code: "VOC", active: true},
  {description: "Viol", ppl_code: "VOL", active: true},
  {description: "Variophon", ppl_code: "VOP", active: true},
  {description: "ValveTrombone", ppl_code: "VTR", active: true},
  {description: "VicitraVina", ppl_code: "VVN", active: true},
  {description: "Weisenborn", ppl_code: "WBN", active: true},
  {description: "Wind Chimes", ppl_code: "WCH", active: true},
  {description: "Woodblock", ppl_code: "WDB", active: true},
  {description: "Wooden Flute", ppl_code: "WFL", active: true},
  {description: "Whistling", ppl_code: "WHG", active: true},
  {description: "Whistle", ppl_code: "WHI", active: true},
  {description: "Whip", ppl_code: "WHP", active: true},
  {description: "Unnamed Wind Instrument", ppl_code: "WND", active: true},
  {description: "Wobble Board", ppl_code: "WOB", active: true},
  {description: "Worship Leader", ppl_code: "WOR", active: true},
  {description: "Washboard", ppl_code: "WSB", active: true},
  {description: "Wurlitzer Organ", ppl_code: "WUO", active: true},
  {description: "Woodwind", ppl_code: "WWD", active: true},
  {description: "Xiao", ppl_code: "XIA", active: true},
  {description: "Xylophone", ppl_code: "XYL", active: true},
  {description: "Xylorimba", ppl_code: "XYR", active: true},
  {description: "Yaktaro", ppl_code: "YAK", active: true},
  {description: "Yangqin", ppl_code: "YAN", active: true},
  {description: "Yatga", ppl_code: "YGA", active: true},
  {description: "Yenjing", ppl_code: "YNJ", active: true},
  {description: "Yodelling", ppl_code: "YOD", active: true},
  {description: "Yunluo", ppl_code: "YUN", active: true},
  {description: "Zampona", ppl_code: "ZAM", active: true},
  {description: "Zarb", ppl_code: "ZAR", active: true},
  {description: "Zeze", ppl_code: "ZEZ", active: true},
  {description: "Zhonghu", ppl_code: "ZHG", active: true},
  {description: "Zil", ppl_code: "ZIL", active: true},
  {description: "Zirbaghalia", ppl_code: "ZIR", active: true},
  {description: "Zither", ppl_code: "ZIT", active: true},
  {description: "Zamr", ppl_code: "ZMR", active: true},
  {description: "Zampogna", ppl_code: "ZPG", active: true},
  {description: "Zurna", ppl_code: "ZRN", active: true},
  {description: "Zumare", ppl_code: "ZUM", active: true},
  {description: "Zurla", ppl_code: "ZUR", active: true}
].each do |pr|
  PerformerRole.find_or_create_by(description: pr[:description], ppl_code: pr[:ppl_code], active: pr[:active])
end

